version: 2

multi-ecosystem-groups:
  all:
    schedule:
      interval: daily
    cooldown:
      default-days: 7

updates:
- package-ecosystem: github-actions
  directory: /
  groups:
    github-actions:
      patterns:
      - '*'
  multi-ecosystem-group: all

- package-ecosystem: cargo
  directory: /
  groups:
    cargo:
      patterns:
      - '*'
  multi-ecosystem-group: all
