repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: 4380fbb73a154b5f5624794c1c78d9719ccc860f  # frozen: v2.16.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix, --trailing-commas]
    exclude: Cargo.lock
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/AndrejOrsula/pre-commit-cargo
  rev: 33ae92ed9b1a4392c8ac5fdef46887640d866e1e  # frozen: 0.5.0
  hooks:
  - id: cargo-fmt
    additional_dependencies: ['serde_json:1.0.150']
  - id: cargo-clippy
    additional_dependencies: ['serde_json:1.0.150']
    args:
    - --all-targets
    - --locked
    - --
    - -D
    - warnings
    - -D
    - clippy::pedantic
    - -D
    - clippy::nursery
    - -D
    - clippy::cargo
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: e3eebf65325ccc992422292cb7a4baee967cf815  # frozen: v1.26.1
  hooks:
  - id: zizmor
    args: [--no-progress, --fix]
